### ISSUE TITLE
After having updated it in "2.4.4", a test fails

### ISSUE THREAD

**Issue by y-yagi** [guard/guard-minitest#128]
After having updated it in "2.4.4", my test came to fail.

stacktrace is as follows:

```ruby 
/home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- guard (LoadError)
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-minitest-2.4.4/lib/minitest/guard_minitest_plugin.rb:4:in `<top (required)>'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:91:in `block in load_plugins'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:85:in `each'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:85:in `load_plugins'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:114:in `run'
	from /home/yaginuma/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:56:in `block in autorun'
```
I seem to fail for `require 'guard'`. 

Originally I did not add `guard` to my `Gemfile`, will it be necessary?

Thanks.

**Comment by e2** [comment]
The short answer is yes - you should include `gem 'guard'` in your Gemfile.

It's a bit tricky to get everything working around guard-minitest, so please do report issues.

Basically, for notification to work, guard-minitest has to use Guard. But since guard-minitest is used for testing other guard plugins, it has to also work without Guard as well (so guard is not a dependency for guard-minitest).

Let me know if you have issues.

**Comment by y-yagi** [comment]
Thank you for explanation! 
No problem.  I add `guard` to my `Gemfile` and cope.

Thanks.
