### ISSUE TITLE
Rails 5 issues: invalid option: --guard

### ISSUE THREAD

**Issue by ZombieHarvester** [guard/guard-minitest#142]
Upgraded to Rails 5 and guard-minitest `v2.4.6` today. Got two issues:
## Problem 1

`bundle exec guard` with `guard :minitest do` i get the following error:

```
/Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options': invalid option: --guard (OptionParser::InvalidOption)
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:200:in `block (2 levels) in process_args'
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:198:in `each'
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:198:in `block in process_args'
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:168:in `new'
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:168:in `process_args'
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:122:in `run'
    from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minitest-5.9.0/lib/minitest.rb:62:in `block in autorun'
```

it might be related to the following issue: https://github.com/rails/rails/issues/25046 and #141

if i add spring to the guardfile `guard :minitest, spring: true do` then `invalid option: --guard` doesn't appear and all tests run . Also rolling back to `v2.4.5` solves the issue.

~~Problem 2~~

~~with `spring: true` i cannot get specific test to run. Having `watch(%r{^test/.+_test\.rb$})` in guardfile and updating for example `user_test.rb` it runs all tests. Without spring it runs only `user_test.rb`~~ see #130

**Comment by e2** [comment]
@tmichel - any ideas for problem 1?

**Comment by e2** [comment]
For problem 2: This probably doesn't help much, it could give ideas: https://github.com/guard/guard-minitest/issues/133

Can you create a mini project to recreate the problem? (I don't have time right now, but if I had a small repo with this issue, I could check exactly what is going on).

**Comment by e2** [comment]
Maybe also related: https://github.com/guard/guard-minitest/issues/130

**Comment by ZombieHarvester** [comment]
thanks @e2, it was #130. Using `spring: "bin/rails test"` solved problem 2. Maybe it needs to be in the readme?

**Comment by tmichel** [comment]
For problem 1 the cause is definitely the linked Rails issue (https://github.com/rails/rails/issues/25046). Rails has its own minitest runner and that parses options ahead of time and minitest plugins could not register their own flags. This probably breaks any other plugin that uses custom command line flags.

Using a flag to signal the plugin is pretty much the recommended minitest way. I don't know if the mentioned Rails bug should be "supported" by guard-minitest and worked around somehow.

**Comment by taq** [comment]
Guys? Seems that 6 months after this issue was open seems that even on the most recent version of the gems (`rails`, `guard`, `guard-minitest`) is still failing to run. Using `spring: true`, as said, works to run Guard, but everytime it runs all the tests, and becomes a little complicated ... we need to wait the resolution on the Rails side, right?

**Comment by tmichel** [comment]
For me the following setup works flawlessly: 

* guard (2.14.0)
* guard-minitest (2.4.6)
* rails 5.0.1

```ruby
# in Guardfile
guard :minitest, spring: "bin/rails test", all_on_start: false do
  # usual rules for Rails apps
end
```

**Comment by taq** [comment]
Hey @tmichel will check it out!

**Comment by Mirv** [comment]
@tmichel thanks! Worked for me

**Comment by taq** [comment]
Worked for me too, thanks @tmichel :-)

**Comment by a-b** [comment]
The main problem with this approach is that run all tests feature is still broken, so you can't hit enter and run all tests.

Right now my guardfile looks like

```rb
    guard :minitest, spring: "ruby -Ilib:test:spec", all_on_start: false do
      watch(%r{^app/(.+)\.rb$})                               { |m| "test/#{m[1]}_test.rb" }
      watch(%r{^app/controllers/application_controller\.rb$}) { 'test/controllers' }
      watch(%r{^app/controllers/(.+)_controller\.rb$})        { |m| "test/integration/#{m[1]}_test.rb" }
      watch(%r{^lib/(.+)\.rb$})                               { |m| "test/lib/#{m[1]}_test.rb" }
      watch(%r{^test/.+_test\.rb$})
      watch(%r{^test/test_helper\.rb$}) { 'test' }
    end
```

it works when some specific file updated. But when I hit enter to run all tests it just run 0 tests

```
16:56:00 - INFO - Guard::Minitest 2.4.6 is running, with Minitest::Unit 5.8.4!
16:56:00 - INFO - Guard is now watching at 'some_code_folder'
[1] guard(main)>
16:56:01 - INFO - Run all
16:56:01 - INFO - Running: all tests
Started with run options --seed 6342

  0/0: [===========================================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00439s
0 tests, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by a-b** [comment]
Any better solution exist?

**Comment by seanlerner** [comment]
Paring down @tmichel's solution, I managed to get away with just:

```ruby
guard :minitest, spring: 'rails test' do
  # rules
end
```

**Comment by starrychloe** [comment]
This is occurring for me too. There's nothing remarkable about my app. I'm not even using Spring. I'm using the default Guardfile generated with `bundle exec guard init minitest`. 

```
>bundle exec guard
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
20:33:43 - INFO - Run 'gem install win32console' to use color on Windows
20:33:44 - INFO - Guard::Minitest 2.4.6 is running, with Minitest::Unit 5.10.1!

20:33:44 - INFO - Running: all tests
C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options': invalid option: --guard (OptionParser::InvalidOption)
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:200:in `block (2 levels) in process_args'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:198:in `each'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:198:in `block in process_args'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:168:in `new'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:168:in `process_args'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:122:in `run'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:72:in `run'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:62:in `block in autorun'
[1] guard(main)>  Guard is now watching at ...
```

Rails tests work fine by themselves.

```
>rails test
Run options: --seed 20239

# Running:
...
```


Rails 5.0.2, Windows

**Comment by skddc** [comment]
I get this error without Rails, in just a plain Ruby gem, that I created with the `bundler gem` command and default minitest layout. When I run it with `guard -d` I see that it indeed does add an additional `-- --guard` option to the command and that minitest does not accept it.

**Comment by yb66** [comment]
I also get this error and I'm not using Rails.

**Comment by rmm5t** [comment]
Closing. The `--guard` option is no longer in v3.0.0
