### ISSUE TITLE
cli option not passing arguments to Minitest CLI properly

### ISSUE THREAD

**Issue by bweave** [guard/guard-minitest#151]
When I try and pass arguments to Minitest CLI via the `cli` option, I get a `cannot load such file -- /path/to/dir/--my_argument` error.

```
$ bundle exec guard start
Expected string default value for '--listen-on'; got false (boolean)
14:02:16 - INFO - Guard::Minitest 2.4.6 is running, with Minitest::Unit 5.10.2!
14:02:16 - INFO - Running: all tests
Running via Spring preloader in process 47165
/Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- /Users/brianweaver/bin/rails-5.1-test/--verbose (LoadError)
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/test_unit/test_requirer.rb:14:in `block in require_files'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/test_unit/test_requirer.rb:13:in `each'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/test_unit/test_requirer.rb:13:in `require_files'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:96:in `plugin_rails_init'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:81:in `block in init_plugins'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:79:in `each'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:79:in `init_plugins'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:130:in `run'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/brianweaver/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

Guardfile

```
guard :minitest, spring: "bin/rails test", cli: "--verbose" do
  watch(%r{^test/.+_test\.rb$})
  watch(%r{^lib/(.*/)?([^/]+)\.rb$})     { |m| "test/#{m[1]}test_#{m[2]}.rb" }
  watch(%r{^test/test_helper\.rb$})      { 'test' }
end
```

Gemfile

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.1'
gem 'sqlite3'
gem 'puma', '~> 3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard'
  gem 'guard-minitest'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

**Comment by bweave** [comment]
Hmm, is [this issue](https://github.com/rails/rails/issues/25046) the underlying culprit?
